#!/usr/bin/python3
from tkinter import *
from tkinter import font
import time
#import RPi.GPIO as GPIO
#import pigpio
import threading

"""raspberry_slave1 = pigpio.pi("192.168.0.2")
raspberry_slave2 = pigpio.pi("192.168.0.3")
raspberry_slave3 = pigpio.pi("192.168.0.4")

raspberry_slave1.set_mode(4, pigpio.OUTPUT)
raspberry_slave1.set_mode(17, pigpio.OUTPUT)
raspberry_slave1.set_mode(18, pigpio.OUTPUT)
raspberry_slave1.set_mode(27, pigpio.OUTPUT)
raspberry_slave1.set_mode(22, pigpio.OUTPUT)
raspberry_slave1.set_mode(23, pigpio.OUTPUT)
raspberry_slave1.set_mode(24, pigpio.OUTPUT)
raspberry_slave1.set_mode(10, pigpio.OUTPUT)
raspberry_slave1.set_mode(9, pigpio.OUTPUT)
raspberry_slave1.set_mode(25, pigpio.OUTPUT)
raspberry_slave1.set_mode(11, pigpio.OUTPUT)
raspberry_slave1.set_mode(8, pigpio.OUTPUT)
raspberry_slave1.set_mode(7, pigpio.OUTPUT)
raspberry_slave1.set_mode(5, pigpio.OUTPUT)
raspberry_slave1.set_mode(6, pigpio.OUTPUT)
raspberry_slave1.set_mode(12, pigpio.OUTPUT)
raspberry_slave2.set_mode(4, pigpio.OUTPUT)
raspberry_slave2.set_mode(17, pigpio.OUTPUT)
raspberry_slave2.set_mode(18, pigpio.OUTPUT)
raspberry_slave2.set_mode(27, pigpio.OUTPUT)
raspberry_slave2.set_mode(22, pigpio.OUTPUT)
raspberry_slave2.set_mode(23, pigpio.OUTPUT)
raspberry_slave2.set_mode(24, pigpio.OUTPUT)
raspberry_slave2.set_mode(10, pigpio.OUTPUT)
raspberry_slave2.set_mode(9, pigpio.OUTPUT)
raspberry_slave2.set_mode(25, pigpio.OUTPUT)
raspberry_slave2.set_mode(11, pigpio.OUTPUT)
raspberry_slave2.set_mode(8, pigpio.OUTPUT)
raspberry_slave2.set_mode(7, pigpio.OUTPUT)
raspberry_slave2.set_mode(5, pigpio.OUTPUT)
raspberry_slave2.set_mode(6, pigpio.OUTPUT)
raspberry_slave2.set_mode(12, pigpio.OUTPUT)
raspberry_slave3.set_mode(4, pigpio.OUTPUT)
raspberry_slave3.set_mode(17, pigpio.OUTPUT)
raspberry_slave3.set_mode(18, pigpio.OUTPUT)
raspberry_slave3.set_mode(27, pigpio.OUTPUT)
raspberry_slave3.set_mode(22, pigpio.OUTPUT)
raspberry_slave3.set_mode(23, pigpio.OUTPUT)
raspberry_slave3.set_mode(24, pigpio.OUTPUT)
raspberry_slave3.set_mode(10, pigpio.OUTPUT)
raspberry_slave3.set_mode(9, pigpio.OUTPUT)
raspberry_slave3.set_mode(25, pigpio.OUTPUT)
raspberry_slave3.set_mode(11, pigpio.OUTPUT)
raspberry_slave3.set_mode(8, pigpio.OUTPUT)
raspberry_slave3.set_mode(7, pigpio.OUTPUT)
raspberry_slave3.set_mode(5, pigpio.OUTPUT)
raspberry_slave3.set_mode(6, pigpio.OUTPUT)
raspberry_slave3.set_mode(12, pigpio.OUTPUT)
raspberry_slave3.set_mode(20, pigpio.OUTPUT)"""

""" entorno grafico """
ventana = Tk()
ventana.title("SPSI")
ventana.configure(background='white')
ventana.minsize(1600, 900) 

##ventana.attributes("-fullscreen",True)


def IniciarM1():
    pminimotxt = Label(ventana,text="holaaaa", font=("Agency FB", 14)).place(x=1400, y=150)

filename = PhotoImage(file = "C:\\Users\\SPSI\\Desktop\\CEREZA Santa Catalina 2019\\PACKING.gif")
background_label = Label(ventana, image=filename)
background_label.place(x=0, y=0, relwidth=1, relheight=1)
imgIzq = PhotoImage(file = "C:\\Users\\SPSI\\Desktop\\CEREZA Santa Catalina 2019\\flechas\\izquierda.png")
imgAbajo = PhotoImage(file = "C:\\Users\\SPSI\\Desktop\\CEREZA Santa Catalina 2019\\flechas\\abajo.png")
imgArriba = PhotoImage(file = "C:\\Users\\SPSI\\Desktop\\CEREZA Santa Catalina 2019\\flechas\\arriba.png")

Calibrador1 = Label(ventana, image=imgIzq)
Calibrador1.place(x=2000, y=2000)
Calibrador2 = Label(ventana, image=imgIzq)
Calibrador2.place(x=2000, y=2000)

Bombas1 = Label(ventana, image=imgAbajo)
Bombas1.place(x=2000, y=2000)
Bombas2 = Label(ventana, image=imgAbajo)
Bombas2.place(x=2000, y=2000)

Confeccion1 = Label(ventana, image=imgAbajo)
Confeccion1.place(x=2000, y=2000)
Confeccion2 = Label(ventana, image=imgAbajo)
Confeccion2.place(x=2000, y=2000)
Confeccion3 = Label(ventana, image=imgAbajo)
Confeccion3.place(x=2000, y=2000)
Confeccion4 = Label(ventana, image=imgAbajo)
Confeccion4.place(x=2000, y=2000)
Confeccion5 = Label(ventana, image=imgAbajo)
Confeccion5.place(x=2000, y=2000)
Confeccion6 = Label(ventana, image=imgAbajo)
Confeccion6.place(x=2000, y=2000)
Confeccion7 = Label(ventana, image=imgAbajo)
Confeccion7.place(x=2000, y=2000)

Sierras1 = Label(ventana, image=imgArriba)
Sierras1.place(x=2000, y=2000)

Vaciado1 = Label(ventana, image=imgArriba)
Vaciado1.place(x=2000, y=2000)

""" RETARDO MOTORES """
retardo = 1
"""FLECHAS DIBUJO"""
def VerFechasCalibrador():
    Calibrador1.place(x=117+280, y=10+105)
    Calibrador2.place(x=117+460, y=10+105)
def OcultaFechasCalibrador():
    Calibrador1.place(x=2000, y=2000)
    Calibrador2.place(x=2000, y=2000)
def VerFlechasBombas():
    Bombas1.place(x=910, y=110)
    Bombas2.place(x=1160, y=110)
def OcultaFlechasBombas():
    Bombas1.place(x=2000, y=2000)
    Bombas2.place(x=2000, y=2000)
def VerFlechasConfeccion():
    Confeccion1.place(x=117+441, y=10+340)
    Confeccion2.place(x=117+566, y=10+340)
    Confeccion3.place(x=117+691, y=10+340)
    Confeccion4.place(x=117+816, y=10+340)
    Confeccion5.place(x=117+941, y=10+340)
    Confeccion6.place(x=117+1066, y=10+340)
    Confeccion7.place(x=117+1191, y=10+340)
def OcultaFlechasConfeccion():
    Confeccion1.place(x=2000, y=2000)
    Confeccion2.place(x=2000, y=2000)
    Confeccion3.place(x=2000, y=2000)
    Confeccion4.place(x=2000, y=2000)
    Confeccion5.place(x=2000, y=2000)
    Confeccion6.place(x=2000, y=2000)
    Confeccion7.place(x=2000, y=2000)
def VerFlechasSierras():
    Sierras1.place(x=117+80, y=10+250)
def OcultarFlechasSierras():
    Sierras1.place(x=2000, y=2000)
def VerFlechasVaciado():
    Vaciado1.place(x=117+80, y=10+430)
def OcultaFlechasVaciado():
    Vaciado1.place(x=2000, y=2000)
"""FUNCIONES BOTONES"""
def IniciarBombas():
    iniciando = Label(ventana,text="Iniciando Zona de Bombas", font=("Agency FB", 20), bg="white", fg="red").place(x=117+520, y=700)
    LEDBombas0 = Button(ventana, text="_", width=2, bg = "lime", fg = "lime",font=("Agency FB", 14)).place(x=117+945, y=10+10)
    btnBombas0 = Button(ventana, text="Parar Zona Bombas",command=PararBombas, width=BtnSize, bg = "red", fg = "white", font=("Agency FB", 14)).place(x=117+978, y=10+10)
    VerFlechasBombas()
    ventana.update()
    time.sleep(3.5)
    """raspberry_slave3.write(5,1)
    time.sleep(retardo)
    raspberry_slave3.write(6,1)
    time.sleep(retardo)
    raspberry_slave3.write(12,1)
    time.sleep(retardo)
    raspberry_slave3.write(13,1)
    time.sleep(retardo)
    raspberry_slave3.write(19,1)
    time.sleep(retardo)
    raspberry_slave3.write(16,1)
    time.sleep(retardo)
    raspberry_slave3.write(26,1)
    time.sleep(retardo)
    raspberry_slave3.write(20,1)"""
    iniciando = Label(ventana,text="Iniciando Zona de Bombas", font=("Agency FB", 20), bg="white", fg="white").place(x=117+520, y=700)
def PararBombas():
    LEDBombas0 = Button(ventana, text="_", width=2, bg = "darkred", fg = "darkred",font=("Agency FB", 14)).place(x=117+945, y=10+10)
    btnBombas0 = Button(ventana, text="Iniciar Zona Bombas",command=IniciarBombas, width=BtnSize, bg = "blue", fg = "white", font=("Agency FB", 14)).place(x=117+978, y=10+10)
    """raspberry_slave3.write(5,0)
    raspberry_slave3.write(6,0)
    raspberry_slave3.write(12,0)
    raspberry_slave3.write(13,0)
    raspberry_slave3.write(19,0)
    raspberry_slave3.write(16,0)
    raspberry_slave3.write(26,0)
    raspberry_slave3.write(20,0)"""
    OcultaFlechasBombas()
def IniciarConfeccion():
    iniciando = Label(ventana,text="Iniciando Zona de Confección", font=("Agency FB", 20), bg="white", fg="red").place(x=117+505, y=700)
    LEDConfecc = Button(ventana, text="_", width=2, bg = "lime", fg = "lime",font=("Agency FB", 14)).place(x=117+846, y=233+10)
    btnConfecc = Button(ventana, text="Parar Zona Confección",command=PararConfeccion, width=BtnSize+3, bg = "red", fg = "white",font=("Agency FB", 14)).place(x=117+879, y=233+10)
    VerFlechasConfeccion()
    ventana.update()
    time.sleep(14.5)
    """raspberry_slave1.write(4, 1)
    time.sleep(retardo)
    #raspberry_slave1.write(17,1)
    time.sleep(retardo)
    #raspberry_slave1.write(18,1)
    time.sleep(retardo)
    #raspberry_slave1.write(27,1)
    time.sleep(retardo)
    #raspberry_slave1.write(22,1)
    time.sleep(retardo)
    #raspberry_slave1.write(23,1)
    time.sleep(retardo)
    #raspberry_slave1.write(24,1)
    time.sleep(retardo)
    #raspberry_slave1.write(10,1)
    time.sleep(retardo)
    #raspberry_slave1.write(9,1)
    time.sleep(retardo)
    #raspberry_slave1.write(25,1)
    time.sleep(retardo)
    #raspberry_slave1.write(11,1)
    time.sleep(retardo)
    #raspberry_slave1.write(8,1)
    time.sleep(retardo)
    #raspberry_slave1.write(7,1)
    time.sleep(retardo)
    #raspberry_slave1.write(5,1)
    time.sleep(retardo)
    #raspberry_slave1.write(6,1)
    time.sleep(retardo)
    #raspberry_slave1.write(12,1)
    time.sleep(retardo)
    #raspberry_slave2.write(4, 1)
    time.sleep(retardo)
    #raspberry_slave2.write(17,1)
    time.sleep(retardo)
    #raspberry_slave2.write(18,1)
    time.sleep(retardo)
    #raspberry_slave2.write(27,1)
    time.sleep(retardo)
    #raspberry_slave2.write(22,1)
    time.sleep(retardo)
    #raspberry_slave2.write(23,1)
    time.sleep(retardo)
    #raspberry_slave2.write(24,1)
    time.sleep(retardo)
    #raspberry_slave2.write(10,1)
    time.sleep(retardo)
    #raspberry_slave2.write(9,1)
    time.sleep(retardo)
    #raspberry_slave2.write(25,1)
    time.sleep(retardo)
    #raspberry_slave2.write(11,1)
    time.sleep(retardo)
    #raspberry_slave2.write(8,1)
    time.sleep(retardo)
    #raspberry_slave2.write(7,1)
    time.sleep(retardo)
    #raspberry_slave2.write(5,1)
    time.sleep(retardo)
    #raspberry_slave2.write(6,1)
    time.sleep(retardo)
    #raspberry_slave2.write(12,1)"""
    iniciando = Label(ventana,text="Iniciando Zona de Confección", font=("Agency FB", 20), bg="white", fg="white").place(x=117+505, y=700)
    
def PararConfeccion():
    LEDConfecc = Button(ventana, text="_", width=2, bg = "darkred", fg = "darkred",font=("Agency FB", 14)).place(x=117+846, y=233+10)
    btnConfecc = Button(ventana, text="Iniciar Zona Confección",command=IniciarConfeccion, width=BtnSize+3, bg = "blue", fg = "white",font=("Agency FB", 14)).place(x=117+879, y=233+10)
    """raspberry_slave1.write(4, 1)
    raspberry_slave1.write(17,0)
    raspberry_slave1.write(18,0)
    raspberry_slave1.write(27,0)
    raspberry_slave1.write(22,0)
    raspberry_slave1.write(23,0)
    raspberry_slave1.write(24,0)
    raspberry_slave1.write(10,0)
    raspberry_slave1.write(9,0)
    raspberry_slave1.write(25,0)
    raspberry_slave1.write(11,0)
    raspberry_slave1.write(8,0)
    raspberry_slave1.write(7,0)
    raspberry_slave1.write(5,0)
    raspberry_slave1.write(6,0)
    raspberry_slave1.write(12,0)
    raspberry_slave2.write(4, 1)
    raspberry_slave2.write(17,0)
    raspberry_slave2.write(18,0)
    raspberry_slave2.write(27,0)
    raspberry_slave2.write(22,0)
    raspberry_slave2.write(23,0)
    raspberry_slave2.write(24,0)
    raspberry_slave2.write(10,0)
    raspberry_slave2.write(9,0)
    raspberry_slave2.write(25,0)
    raspberry_slave2.write(11,0)
    raspberry_slave2.write(8,0)
    raspberry_slave2.write(7,0)
    raspberry_slave2.write(5,0)
    raspberry_slave2.write(6,0)
    raspberry_slave2.write(12,0)"""
    OcultaFlechasConfeccion()
def IniciarCalibrador():
    iniciando = Label(ventana,text="Iniciando Zona de Calibración", font=("Agency FB", 20), bg="white", fg="red").place(x=117+500, y=700)
    LEDCalibra = Button(ventana, text="_", width=2, bg = "lime", fg = "lime",font=("Agency FB", 14)).place(x=117+337, y=10+10)
    btnCalibra = Button(ventana, text="Parar Zona Calibrador",command=PararCalibrador, width=BtnSize+2, bg = "red", fg = "white",font=("Agency FB", 14)).place(x=117+370, y=10+10)
    VerFechasCalibrador()
    ventana.update()
    time.sleep(1.5)
    """raspberry_slave3.write(27,1)
    time.sleep(0.5)
    raspberry_slave3.write(22,1)
    time.sleep(0.5)
    raspberry_slave3.write(23,1)
    time.sleep(0.5)
    raspberry_slave3.write(24,1)
    time.sleep(0.5)
    raspberry_slave3.write(10,1)"""
    iniciando = Label(ventana,text="Iniciando Zona de Calibración", font=("Agency FB", 20), bg="white", fg="white").place(x=117+500, y=700)
def PararCalibrador():
    LEDCalibra = Button(ventana, text="_", width=2, bg = "darkred", fg = "darkred",font=("Agency FB", 14)).place(x=117+337, y=10+10)
    btnCalibra = Button(ventana, text="Iniciar Zona Calibrador",command=IniciarCalibrador, width=BtnSize+2, bg = "blue", fg = "white",font=("Agency FB", 14)).place(x=117+370, y=10+10)
    """raspberry_slave3.write(27,0)
    raspberry_slave3.write(22,0)
    raspberry_slave3.write(23,0)
    raspberry_slave3.write(24,0)
    raspberry_slave3.write(10,0)"""
    OcultaFechasCalibrador()
def IniciarSierras():
    iniciando = Label(ventana,text="Iniciando Zona de Sierras", font=("Agency FB", 20), bg="white", fg="red").place(x=117+525, y=700)
    LEDCierras = Button(ventana, text="_", width=2, bg = "lime", fg = "lime",font=("Agency FB", 14)).place(x=117+127, y=225+10)
    btnCierras = Button(ventana, text="Parar Zona Sierras",command=PararSierras, width=BtnSize, bg = "red", fg = "white",font=("Agency FB", 14)).place(x=117+160, y=225+10)
    VerFlechasSierras()
    ventana.update()
    time.sleep(1)
    """raspberry_slave3.write(4,1)
    time.sleep(0.5)
    raspberry_slave3.write(17,1)
    time.sleep(0.5)
    raspberry_slave3.write(18,1)"""
    iniciando = Label(ventana,text="Iniciando Zona de Sierras", font=("Agency FB", 20), bg="white", fg="white").place(x=117+525, y=700)
def PararSierras():
    LEDCierras = Button(ventana, text="_", width=2, bg = "darkred", fg = "darkred",font=("Agency FB", 14)).place(x=117+127, y=225+10)
    btnCierras = Button(ventana, text="Iniciar Zona Sierras",command=IniciarSierras, width=BtnSize, bg = "blue", fg = "white",font=("Agency FB", 14)).place(x=117+160, y=225+10)
    """raspberry_slave3.write(4,0)
    raspberry_slave3.write(17,0)
    raspberry_slave3.write(18,0)"""
    OcultarFlechasSierras()
def IniciarVaciado():
    iniciando = Label(ventana,text="Iniciando Zona de Vaciado", font=("Agency FB", 20), bg="white", fg="red").place(x=117+525, y=700)
    LEDVaciado = Button(ventana, text="_", width=2, bg = "lime", fg = "lime",font=("Agency FB", 14)).place(x=117+135, y=485+10)
    btnVaciado = Button(ventana, text="Parar Zona Vaciado",command=PararVaciado, width=BtnSize, bg = "red", fg = "white",font=("Agency FB", 14)).place(x=117+168, y=485+10)
    VerFlechasVaciado()
    ventana.update()
    time.sleep(2)
    """raspberry_slave3.write(9,1)
    time.sleep(0.5)
    raspberry_slave3.write(25,1)
    time.sleep(0.5)
    raspberry_slave3.write(11,1)
    time.sleep(0.5)
    raspberry_slave3.write(8,1)
    time.sleep(0.5)
    raspberry_slave3.write(7,1)"""
    iniciando = Label(ventana,text="Iniciando Zona de Vaciado", font=("Agency FB", 20), bg="white", fg="white").place(x=117+525, y=700)
def PararVaciado():
    LEDVaciado = Button(ventana, text="_", width=2, bg = "darkred", fg = "darkred",font=("Agency FB", 14)).place(x=117+135, y=485+10)
    btnVaciado = Button(ventana, text="Iniciar Zona Vaciado",command=IniciarVaciado, width=BtnSize, bg = "blue", fg = "white",font=("Agency FB", 14)).place(x=117+168, y=485+10)
    """raspberry_slave3.write(9,0)
    raspberry_slave3.write(25,0)
    raspberry_slave3.write(11,0)
    raspberry_slave3.write(8,0)
    raspberry_slave3.write(7,0)"""
    OcultaFlechasVaciado()
    
BtnSize = 15
LEDConfecc = Button(ventana, text="_", width=2, bg = "darkred", fg = "darkred",font=("Agency FB", 14)).place(x=117+846, y=233+10)
btnConfecc = Button(ventana, text="Iniciar Zona Confección",command=IniciarConfeccion, width=BtnSize+3, bg = "blue", fg = "white",font=("Agency FB", 14)).place(x=117+879, y=233+10)
LEDVaciado = Button(ventana, text="_", width=2, bg = "darkred", fg = "darkred",font=("Agency FB", 14)).place(x=117+135, y=485+10)
btnVaciado = Button(ventana, text="Iniciar Zona Vaciado",command=IniciarVaciado, width=BtnSize, bg = "blue", fg = "white",font=("Agency FB", 14)).place(x=117+168, y=485+10)
LEDCierras = Button(ventana, text="_", width=2, bg = "darkred", fg = "darkred",font=("Agency FB", 14)).place(x=117+127, y=225+10)
btnCierras = Button(ventana, text="Iniciar Zona Sierras",command=IniciarSierras, width=BtnSize, bg = "blue", fg = "white",font=("Agency FB", 14)).place(x=117+160, y=225+10)
LEDCalibra = Button(ventana, text="_", width=2, bg = "darkred", fg = "darkred",font=("Agency FB", 14)).place(x=117+337, y=10+10)
btnCalibra = Button(ventana, text="Iniciar Zona Calibrador",command=IniciarCalibrador, width=BtnSize+2, bg = "blue", fg = "white",font=("Agency FB", 14)).place(x=117+370, y=10+10)
LEDBombas0 = Button(ventana, text="_", width=2, bg = "darkred", fg = "darkred",font=("Agency FB", 14)).place(x=117+945, y=10+10)
btnBombas0 = Button(ventana, text="Iniciar Zona Bombas",command=IniciarBombas, width=BtnSize, bg = "blue", fg = "white", font=("Agency FB", 14)).place(x=117+978, y=10+10)


def IniciarGeneral():
    iniciando = Label(ventana,text="Iniciando...", font=("Agency FB", 20), bg="white", fg="red").place(x=117+610, y=700)
    ventana.update()
    IniciarBombas()
    IniciarConfeccion()
    IniciarCalibrador()
    IniciarSierras()
    IniciarVaciado()
    iniciando = Label(ventana,text="Iniciando...", font=("Agency FB", 20), bg="white", fg="white").place(x=117+610, y=700)
    ventana.update()
def PararGeneral():
    PararBombas()
    PararConfeccion()
    PararCalibrador()
    PararSierras()
    PararVaciado()
    
btnIniciar = Button(ventana, text="Iniciar",command=IniciarGeneral, width=BtnSize-5, bg = "blue", fg = "white",font=("Agency FB", 14)).place(x=117+5, y=10+10)
btnParar00 = Button(ventana, text="Parar",command=PararGeneral, width=BtnSize-5, bg = "red", fg = "white",font=("Agency FB", 14)).place(x=117+130, y=10+10)


ventana.mainloop()
